/* empty css                      */import{i as a,S as l}from"./assets/vendor-BvSoRH6M.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const i={searchForm:document.querySelector(".js-search-form"),searchInput:document.querySelector(".js-search-input"),gallery:document.querySelector(".js-gallery"),notFoundText:document.querySelector(".js-not-found-text")},u="https://pixabay.com/api/",f="49309172-5f8130b15ef3c43c70e2ee30a",m="photo",d="horizontal",y="true";function p(s){const o=new URLSearchParams({key:f,q:s,image_type:m,orientation:d,safesearch:y});return fetch(`${u}?${o}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const h=()=>{a.error({title:"❌ Please, enter a query!",message:"",position:"topCenter",color:"red",icon:""})},g=()=>{a.error({title:"❌ Sorry, there are no images matching your search query. Please try again!",message:"",position:"topCenter",color:"red",icon:""})};function S(s){return s.map(({webformatURL:o,largeImageURL:t,tags:n,likes:e,views:r,comments:c,downloads:L})=>`<li class="gallery-card">
      <a class="gallery-link" href="${t}">
        <img
        class="gallery-img"
        src="${o}"
        alt="${n}">
      </a>
    </li>`).join("")}new l(".gallery-link",{captionsData:"alt",captionDelay:250,overlayOpacity:1});function E(s){s.preventDefault();const o=s.currentTarget,t=o.elements.user_query.value.trim();if(!t)return h();console.log(t),p(t).then(n=>{if(!n.total)return g();console.log(n.hits),i.gallery.innerHTML=S(n.hits)}).catch(n=>{console.log(n)}),o.reset()}i.searchForm.addEventListener("submit",E);
//# sourceMappingURL=search.js.map
