/* empty css                      */import{i as c,S as l}from"./assets/vendor-BvSoRH6M.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const i={searchForm:document.querySelector(".js-search-form"),searchInput:document.querySelector(".js-search-input"),gallery:document.querySelector(".js-gallery"),notFoundText:document.querySelector(".js-not-found-text")},u="https://pixabay.com/api/",f="49309172-5f8130b15ef3c43c70e2ee30a",m="photo",d="horizontal",y="true";function p(s){const t=new URLSearchParams({key:f,q:s,image_type:m,orientation:d,safesearch:y});return fetch(`${u}?${t}`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}const h=()=>{c.error({title:"❌ Please, enter a query!",message:"",position:"topCenter",color:"red",icon:""})},g=()=>{c.error({title:"❌ Sorry, there are no images matching your search query. Please try again!",message:"",position:"topCenter",color:"red",icon:""})};function S(s){return s.map(({webformatURL:t,largeImageURL:o,tags:n,likes:e,views:r,comments:a,downloads:L})=>`<li class="gallery-card">
      <a class="gallery-link" href="${o}">
        <img
        class="gallery-img"
        src="${t}"
        alt="${n}">
      </a>
    </li>`).join("")}new l(".gallery-link",{captionsData:"alt",captionDelay:250,overlayOpacity:1});function E(s){s.preventDefault();const t=s.currentTarget,o=t.elements.user_query.value.trim();if(!o)return h();p(o).then(n=>{if(!n.total)return g();i.gallery.innerHTML=S(n.hits)}).catch(n=>{console.log(n)}),t.reset()}i.searchForm.addEventListener("submit",E);
//# sourceMappingURL=search.js.map
